### PR TITLE
Improved Docs

### PR DESCRIPTION
**Pull request by rutuja2807**

### CODE REVIEW

**Review by thehairy — CHANGES_REQUESTED** [review]
Stop shitposting PR's.
Make a real contribution and stop spamming useless PR's.

**Comment by jeffstahlnecker** [comment]
A bit ridiculous. There's not even a real project being worked on here yet. 😆

**Comment by thehairy** [comment]
Even without a real project, we need to stop those spammers just because they want the shirt from Hacktober. xD

**Comment by jeffstahlnecker** [comment]
Eigentlich lebe ich in Deutschland, aber ich komme aus den USA. 

Yes spammers must be stopped. Though this year, perhaps they want to plant a tree?

**Comment by thehairy** [comment]
Dann ein verspätetes "Willkommen in Deutschland". :P

Impossible! They don't care about the future, they are poor and need the T-Shirt. xD

**Pull request closed without merging**
